import Modal from '@/components/Modal'
import './globals.css'


export const metadata = {
  title: 'Trello Clone AI',
  description: 'Generated by Brigita B for learning purposes',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F8F8FF]'>{children}
      <Modal />
      </body>
    </html>
  )
}


